[workspace]
members = [
    "programs/*",
#    "token-metadata/",
#    "token-vault/",

#    "rust/*",
#    "nft-candy-machine/",
#    "fair-launch/",
#    "auction/program",
#    "metaplex/program",
#    "metaplex/test",
#    "token-vault/test",
#    "token-metadata/test",
]
exclude = [
]
